### ISSUE TITLE
Exception：unexpected EOF

### ISSUE THREAD

**Issue by cnryb** [techotaku/v2ray-dotnet-sdk#1]
system： windows 
dotnet core version：3.0.100-preview6-012264
V2Ray version： 4.18.0

v2ray-dotnet-sdk version：4.18.0
Google.Protobuf version：3.6.1
Grpc version：1.19.0

.net core code
```
var channel = new Channel("127.0.0.1:10086", ChannelCredentials.Insecure);
HandlerServiceClient client = new HandlerServiceClient(channel);
RemoveUserOperation removeUserOperation = new RemoveUserOperation
{
	Email = "a@b.c"
};
var r = client.AlterInbound(new AlterInboundRequest
{
	Tag = "vss",
	Operation = new TypedMessage
	{
		Type = "v2ray.core.app.proxyman.command.RemoveUserOperation",
		Value = Google.Protobuf.ByteString.CopyFromUtf8(removeUserOperation.ToString())
	}
});

```
Exception：			
			Grpc.Core.RpcException:“Status(StatusCode=Unknown, Detail="v2ray.com/core/app/proxyman/command: unknown operation > unexpected EOF")”

Can you help me

**Comment by techotaku** [comment]
How about .NET Core 2.2?

**Comment by cnryb** [comment]
On .NET Core  2.2.300, has the same exception.

**Comment by cnryb** [comment]
ubuntu 18.04
.net core 2.2.300
has the same exception.

**Comment by techotaku** [comment]
OK. I'm trying to reproduce it.

**Comment by techotaku** [comment]
@cnryb Sorry, I didn't look at your code carefully. :wink:
Just use `removeUserOperation.ToByteString()` instead of `ByteString.CopyFromUtf8()`.

**Comment by cnryb** [comment]
You are right.
