### ISSUE TITLE
Any docs of this SDK ?

### ISSUE THREAD

**Issue by GF-Huang** [techotaku/v2ray-dotnet-sdk#2]

**Comment by techotaku** [comment]
No. 😢 
Emmm... may add samples later.

**Comment by GF-Huang** [comment]
Is it include the v2ray client protocol implemention ? I read the source just see a few `config.cs`. It seems not like client implemention. 🤔

**Comment by techotaku** [comment]
Yes, of course.

That implement is generated code.

For example: 
Stats Service API client  
[V2Ray.Core.App.Stats.Command.StatsService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/stats/command/CommandGrpc.cs#L56)    
Handler Service API client  
[V2Ray.Core.App.Proxyman.Command.HandlerService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/proxyman/command/CommandGrpc.cs#L112)

**Comment by GF-Huang** [comment]
> Yes, of course.
> 
> That implement is generated code.
> 
> For example:
> Stats Service API client
> [V2Ray.Core.App.Stats.Command.StatsService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/stats/command/CommandGrpc.cs#L56)
> Handler Service API client
> [V2Ray.Core.App.Proxyman.Command.HandlerService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/proxyman/command/CommandGrpc.cs#L112)

I think this is an SDK to control to `V2Ray Core` .. But not the Core Implemention..

**Comment by techotaku** [comment]
> > Yes, of course.
> > That implement is generated code.
> > For example:
> > Stats Service API client
> > [V2Ray.Core.App.Stats.Command.StatsService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/stats/command/CommandGrpc.cs#L56)
> > Handler Service API client
> > [V2Ray.Core.App.Proxyman.Command.HandlerService.StatsServiceClient](https://github.com/techotaku/v2ray-dotnet-sdk/blob/master/sdk/app/proxyman/command/CommandGrpc.cs#L112)
> 
> I think this is an SDK to control to `V2Ray Core` .. But not the Core Implemention..

You are right.
There may be a misunderstanding here, let me clarify:
In this thread, `v2ray client protocol implemention` means `V2Ray Grpc API Client Implemention` for me. :]

**Comment by GF-Huang** [comment]
Thank you for your clarify. :)

**Comment by Lua12138** [comment]
Any docs about `AddOutboundRequest` or `AddInboundRequest` ?
