### ISSUE TITLE
Can this be used in xamarin?

### ISSUE THREAD

**Issue by bbhxwl** [techotaku/v2ray-dotnet-sdk#3]
Can this be used in xamarin?

I want to develop v2ray for Android and IOS

**Comment by techotaku** [comment]
- The [sdk nuget package](https://www.nuget.org/packages/V2Ray.SDK/4.26.0):  
> Based on .NET Standard 1.5, Xamarin.iOS 10.0 or Xamarin.Android 7.0 is required.  
> For more information, check [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).  

- But this [tool project](https://github.com/techotaku/v2ray-dotnet-sdk/tree/master/tool) has only been tested under Windows.

**Comment by bbhxwl** [comment]
> * The [sdk nuget package](https://www.nuget.org/packages/V2Ray.SDK/4.26.0):
> 
> > Based on .NET Standard 1.5, Xamarin.iOS 10.0 or Xamarin.Android 7.0 is required.
> > For more information, check [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
> 
> * But this [tool project](https://github.com/techotaku/v2ray-dotnet-sdk/tree/master/tool) has only been tested under Windows.

If we can support. Net standard 2.0 and develop custom VPN protocol in IOS and Android, it will be a great project,.

**Comment by techotaku** [comment]
There may be a misunderstanding here, let me clarify:
This project is V2Ray Grpc API client implemention, an SDK to interact with a running V2Ray server, **NOT** the dotnet implemention of V2Ray Core.
If you are looking for a VMESS protocol client implement, this project does not meet your requirements.
